/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.misiontic.reto5;

import com.misiontic.reto5.controller.ReportesController;
import com.misiontic.reto5.model.Vo.CompraPorProveedorVo;
import com.misiontic.reto5.model.Vo.LiderPorCiudadVo;
import com.misiontic.reto5.model.Vo.ProyectoUbicacionVo;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author javie
 */
public class frmRequerimientos extends javax.swing.JFrame {

    /**
     * Creates new form frmRequerimientos
     */
    public frmRequerimientos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton1.setText("Informe 1");
        jButton1.setAlignmentY(0.0F);
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setMargin(new java.awt.Insets(40, 50, 20, 50));
        jButton1.setMaximumSize(new java.awt.Dimension(100, 20));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 20));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 100, 41));

        jButton2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton2.setText("Informe 2");
        jButton2.setAlignmentY(0.0F);
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setMargin(new java.awt.Insets(20, 200, 20, 50));
        jButton2.setMaximumSize(new java.awt.Dimension(100, 20));
        jButton2.setMinimumSize(new java.awt.Dimension(100, 20));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 40));
        jButton2.setSelected(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jButton3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton3.setText("Informe 3");
        jButton3.setAlignmentY(0.0F);
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.setMargin(new java.awt.Insets(20, 350, 20, 50));
        jButton3.setMaximumSize(new java.awt.Dimension(100, 40));
        jButton3.setMinimumSize(new java.awt.Dimension(100, 40));
        jButton3.setPreferredSize(new java.awt.Dimension(100, 40));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setPreferredSize(new java.awt.Dimension(400, 350));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 340));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\javie\\OneDrive\\Escritorio\\Recursos\\Fondo.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, -80, 760, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String[] columnNombre = {"Id Lider", "Nombre", "Primer Apellido", "Residencia"};
        ReportesController controlador = new ReportesController();
        ArrayList<LiderPorCiudadVo> listaA;
        
        try {
            listaA = controlador.consultarLiderPorCiudad();
            Object[][] datos = new Object[listaA.size()][4];
            int index = 0;
            for (LiderPorCiudadVo lista: listaA){
                datos[index][0] = lista.getIdLider();
                datos[index][1] = lista.getNombre();
                datos[index][2] = lista.getPrimerApellido();
                datos[index][3] = lista.getCiudadResidencia();
                index++;
            }
            
            DefaultTableModel model = new DefaultTableModel(datos, columnNombre);
            jTable1.setModel(model);

        } catch (SQLException e){
		System.err.println(e.getMessage());
}
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String[] columnNombre = {"Id Proyecto", "Constructora", "Numero_Habitaciones", "Ciudad"};
        ReportesController controlador = new ReportesController();
        ArrayList<ProyectoUbicacionVo> listaB;

        try {
            listaB = controlador.consultarProyectoUbicacion();
            Object[][] datos = new Object[listaB.size()][4];
            int index = 0;
            for (ProyectoUbicacionVo lista : listaB) {
                datos[index][0] = lista.getIdProyecto();
                datos[index][1] = lista.getConstructora();
                datos[index][2] = lista.getNumeroHabitaciones();
                datos[index][3] = lista.getCiudad();
                index++;
            }

            DefaultTableModel model = new DefaultTableModel(datos, columnNombre);
            jTable1.setModel(model);

        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String[] columnNombre = {"Id Compra", "Constructora", "Banco Vinculado"};
        ReportesController controlador = new ReportesController();
        ArrayList<CompraPorProveedorVo> listaC;
        
        try {
            listaC = controlador.consultarCompraPorProveedor();
            Object[][] datos = new Object[listaC.size()][3];
            int index = 0;
            for (CompraPorProveedorVo lista: listaC){
                datos[index][0] = lista.getIdCompra();
                datos[index][1] = lista.getConstructora();
                datos[index][2] = lista.getBancoVinculado();
                index++;
            }
            
            DefaultTableModel model = new DefaultTableModel(datos, columnNombre);
            jTable1.setModel(model);

        } catch (SQLException e){
		System.err.println(e.getMessage());
}
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRequerimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRequerimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
